### Create Review
POST http://localhost:5001/api/reviews
Content-Type: application/json

{
  "petId": "pet1234",
  "uid": "user123",
  "petName": "Tiger",
  "userId": "reviewer123",
  "userName": "John",
  "content": "ทดสอบรีวิว"
}

### Get Reviews
GET http://localhost:5001/api/reviews/pet1234